### ISSUE TITLE
2020.6 版本更新 激活无效

### ISSUE THREAD

**Issue by YandexLeetCode** [Hlittled/studio_3t_trial#15]
2020.6 升级了 激活失效了

**Comment by Hlittled** [comment]
合并了一个PR, 最新版可以了

**Comment by jackyting825** [comment]
![image](https://user-images.githubusercontent.com/8901160/87523484-91778500-c6b9-11ea-83ba-6933458bc84c.png)
我下载的最新版本还是激活不了?

**Comment by Hlittled** [comment]
![image](https://user-images.githubusercontent.com/30609790/87526025-e072e980-c6bc-11ea-97f3-1c164ef07855.png)
我最新版本2020.6.1在win10上测试通过, 其他系统没测试过
