### ISSUE TITLE
mac有可能能用吗?

### ISSUE THREAD

**Issue by gotexis** [Hlittled/studio_3t_trial#3]
如题~既然是javaagent补丁，应该都能用不过可否作者来分享下

**Comment by tim5go** [comment]
@gotexis 
It also works on Mac, just a bit tricky.
I assume you installed Studio 3T on Applications folder, then put the crack.jar into:
`Applications/Studio 3T.app/Contents/Resources/app/studio_3t_crack-1.3.jar`

As usual, modify the `vmoptions.txt` by adding the following line:
`-javaagent:/Applications/Studio 3T.app/Contents/Resources/app/studio_3t_crack-1.3.jar`

**Comment by Hlittled** [comment]
没有mac, 没试过, 都是java, 应该能用, 也没什么改动

**Comment by gotexis** [comment]
So, packing on Mac or Windows doesn't matter ? 
I will try and report back.
Btw, I think there is a even easier method, i think just remove whatever file created in usr folder.

@tim5go

**Comment by tim5go** [comment]
@gotexis 
"Packing" you mean building the `jar` file, right?
Java is platform independent for 99.99% of the cases.
So, it shouldn't be a problem. You can build on Windows or Mac

**Comment by gotexis** [comment]
@tim5go Thanks for your assist!

I had success using it on the latest version following your steps. Also, I think it is good to know that Java is platform-agnostic, thank you!

Cheers

**Comment by MaximAndreevich** [comment]
As you could expect, it works for Linux too.
-javaagent:/opt/studio3t/studio_3t_crack-1.5.jar

Just download ZIP. Open it in Idea as a project. Press execute maven target in maven menu.
Choose target Package. Place .jar file from target folder, to program folder. Correct vmopts.
![Screenshot from 2020-04-19 16-34-42](https://user-images.githubusercontent.com/10937359/79689165-b21b7480-825b-11ea-9334-d298ed02f2b6.png)
