### ISSUE TITLE
Broken by update 2020.3.0 (06-Mar-2020)

### ISSUE THREAD

**Issue by gotexis** [Hlittled/studio_3t_trial#5]
2020.3.0 (06-Mar-2020)
======================
- New: Connection Configuration - Improved interface for different connection types.
- Fix: Table View - Fixed a crash that could occur when dragging values during a running operation.
- Fix: Aggregation Editor - Fixed appearance of pipeline and stage result views in Dark Mode.
- Fix: Aggregation Editor - Fixed shortcut ALT + '7' for users of non-international keyboard layouts.
- Fix: Data Compare and Sync - Fixed an error that could occur with documents that have many children.
- Fix: Refresh View - Fixed menu entries and shortcuts for "Refresh View".
- Improved: MongoDB Tool Bundles - Updated bundled MongoDB tools for version 4.0.
- Improved: Application Startup on Linux - Improved long startup times of Studio 3T on Linux.

2020.2.1 (18-Feb-2020)

**Comment by Hlittled** [comment]
updated
