### ISSUE TITLE
2020.3.1 不能用了

### ISSUE THREAD

**Issue by gs-liut** [Hlittled/studio_3t_trial#6]
2020.3.1 不能用了

**Comment by Hlittled** [comment]
新版本混淆后的类名和方法名又变了, 不要用这个了, 直接用删除安装日期相关文件的脚本吧, 比较稳又简单, 再加个开机自动执行脚本就更稳了
https://github.com/Hlittled/studio-3t-trial

**Comment by gs-liut** [comment]
好的，感谢

**Comment by Hlittled** [comment]
jar包补丁的也更新了

**Comment by gs-liut** [comment]
好用！非常感谢！
