### ISSUE TITLE
mac 如何配置

### ISSUE THREAD

**Issue by hcliu987** [Hlittled/studio_3t_trial#7]
mac上的打包之后，应该在什么路径在配置

**Comment by Hlittled** [comment]
没用过mac, jar包放置在`data-man-mongodb-ent-2020.X.X.jar`的同级目录中, 并在`Studio 3T.vmoptions`文件中配置一下, 应该就可以了, 可以参考下这个 #3

**Comment by hcliu987** [comment]
![WeChata425f80e875ad577fba2995ffb98b0a1](https://user-images.githubusercontent.com/52879991/76717505-99a4cf80-676e-11ea-9731-87649c796beb.png)
这个为mac的目录，studio 3t. vmoptions没找到

**Comment by Hlittled** [comment]
mac上应该是修改vmoptions.txt
![截图](https://user-images.githubusercontent.com/30609790/76717916-15ebe280-6770-11ea-8a8f-b4c96ad6efbf.png)

**Comment by hcliu987** [comment]
谢谢
