### ISSUE TITLE
Not working on 2020.4.0

### ISSUE THREAD

**Issue by daopapp** [Hlittled/studio_3t_trial#8]
This trial trick was awesome working on 2020.3.0.
Since the last update(today), after the update, I reinstaled the jar and change the vmoptions.
Now the app doesn't open

**Comment by Hlittled** [comment]
Updated.

**Comment by daopapp** [comment]
Tks man works for me.
One trick for who will update:
 - First, update the Studio3t
- Open the app, it will tell you that your license it's ended.
- Close the app.
- Do the java trick.
- Re-open the app.
- Enjoy!

**Comment by adamwinn** [comment]
I can't get this to work.  I'm on a Mac.  I'm using 2020.4.0

I put the .jar file in `/Applications/Studio 3T.app/Contents/Resources/app/studio_3t_crack-1.5.jar`.  

My `vmoptions.txt` txt file is:
```
# Enter one VM parameter per line
# For example, to adjust the maximum memory usage to 512 MB, uncomment the following line:
# -Xmx512m
# To include another file, uncomment the following line:
# -include-options [path to other .vmoption file]
-javaagent:/Applications/Studio 3T.app/Contents/Resources/app/studio_3t_crack-1.5.jar
```
The app launches but hangs and is unresponsive and no windows open
![Screen Shot 2020-04-15 at 10 40 07 AM](https://user-images.githubusercontent.com/3028964/79363862-b49d6780-7f05-11ea-9319-5ea3455ed957.jpg)

**Comment by daopapp** [comment]
Try to reinstall from studio3t.
After install, open studio3.
Exit.
insert the jar on folder
update vmoptions
reopen studio

**Comment by adamwinn** [comment]
That's exactly what I did and it wont open

**Comment by letrungtrung** [comment]
i had a license valid until Thursday, April 23, 2020. And i did like your guide to reset trial, but when re-opening 3t studio, like old license. Please help me, thanks a lot

**Comment by rsb007** [comment]
I am not able to find studio_3t_crack-1.5.jar

**Comment by daopapp** [comment]
Works on 2020.5.0???
